version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    image: mobiusdocker/admin-app:latest
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      PORT: ${PORT:-8080}
    depends_on:
      - rabbit
      - memcache
  rabbit:
    image: library/rabbitmq:3
    hostname: host-rabbitmq
    ports:
      - 5672:5672
  memcache:
    image: library/memcached:latest
    hostname: host-memcache
    ports:
      - 11211:11211

